// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wire-example/internal/config"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	configConfig, cleanup, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	app := NewApp(configConfig)
	return app, func() {
		cleanup()
	}, nil
}
