// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto/user_enum.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserEnum_SexEnum int32

const (
	UserEnum_UNKNOWN UserEnum_SexEnum = 0 //proto3版本中，首成员必须为0，成员不应有相同的值
	UserEnum_BOY     UserEnum_SexEnum = 1
	UserEnum_GIRL    UserEnum_SexEnum = 2
)

// Enum value maps for UserEnum_SexEnum.
var (
	UserEnum_SexEnum_name = map[int32]string{
		0: "UNKNOWN",
		1: "BOY",
		2: "GIRL",
	}
	UserEnum_SexEnum_value = map[string]int32{
		"UNKNOWN": 0,
		"BOY":     1,
		"GIRL":    2,
	}
)

func (x UserEnum_SexEnum) Enum() *UserEnum_SexEnum {
	p := new(UserEnum_SexEnum)
	*p = x
	return p
}

func (x UserEnum_SexEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserEnum_SexEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_enum_proto_enumTypes[0].Descriptor()
}

func (UserEnum_SexEnum) Type() protoreflect.EnumType {
	return &file_proto_user_enum_proto_enumTypes[0]
}

func (x UserEnum_SexEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserEnum_SexEnum.Descriptor instead.
func (UserEnum_SexEnum) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_enum_proto_rawDescGZIP(), []int{0, 0}
}

type UserEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sex  UserEnum_SexEnum `protobuf:"varint,2,opt,name=sex,proto3,enum=api.UserEnum_SexEnum" json:"sex,omitempty"`
}

func (x *UserEnum) Reset() {
	*x = UserEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_enum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEnum) ProtoMessage() {}

func (x *UserEnum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_enum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEnum.ProtoReflect.Descriptor instead.
func (*UserEnum) Descriptor() ([]byte, []int) {
	return file_proto_user_enum_proto_rawDescGZIP(), []int{0}
}

func (x *UserEnum) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserEnum) GetSex() UserEnum_SexEnum {
	if x != nil {
		return x.Sex
	}
	return UserEnum_UNKNOWN
}

var File_proto_user_enum_proto protoreflect.FileDescriptor

var file_proto_user_enum_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x75,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x72, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x03,
	0x73, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x53, 0x65, 0x78, 0x45, 0x6e, 0x75, 0x6d,
	0x52, 0x03, 0x73, 0x65, 0x78, 0x22, 0x29, 0x0a, 0x07, 0x53, 0x65, 0x78, 0x45, 0x6e, 0x75, 0x6d,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x42, 0x4f, 0x59, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x49, 0x52, 0x4c, 0x10, 0x02,
	0x42, 0x0b, 0x5a, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_user_enum_proto_rawDescOnce sync.Once
	file_proto_user_enum_proto_rawDescData = file_proto_user_enum_proto_rawDesc
)

func file_proto_user_enum_proto_rawDescGZIP() []byte {
	file_proto_user_enum_proto_rawDescOnce.Do(func() {
		file_proto_user_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_user_enum_proto_rawDescData)
	})
	return file_proto_user_enum_proto_rawDescData
}

var file_proto_user_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_user_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_user_enum_proto_goTypes = []interface{}{
	(UserEnum_SexEnum)(0), // 0: api.UserEnum.SexEnum
	(*UserEnum)(nil),      // 1: api.UserEnum
}
var file_proto_user_enum_proto_depIdxs = []int32{
	0, // 0: api.UserEnum.sex:type_name -> api.UserEnum.SexEnum
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_user_enum_proto_init() }
func file_proto_user_enum_proto_init() {
	if File_proto_user_enum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_user_enum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_user_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_enum_proto_goTypes,
		DependencyIndexes: file_proto_user_enum_proto_depIdxs,
		EnumInfos:         file_proto_user_enum_proto_enumTypes,
		MessageInfos:      file_proto_user_enum_proto_msgTypes,
	}.Build()
	File_proto_user_enum_proto = out.File
	file_proto_user_enum_proto_rawDesc = nil
	file_proto_user_enum_proto_goTypes = nil
	file_proto_user_enum_proto_depIdxs = nil
}
