// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto/user_map.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Points map[string]int32 `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *UserMap) Reset() {
	*x = UserMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_map_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMap) ProtoMessage() {}

func (x *UserMap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_map_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMap.ProtoReflect.Descriptor instead.
func (*UserMap) Descriptor() ([]byte, []int) {
	return file_proto_user_map_proto_rawDescGZIP(), []int{0}
}

func (x *UserMap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserMap) GetPoints() map[string]int32 {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_proto_user_map_proto protoreflect.FileDescriptor

var file_proto_user_map_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x8a, 0x01, 0x0a, 0x07,
	0x55, 0x73, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x1a, 0x39, 0x0a,
	0x0b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_user_map_proto_rawDescOnce sync.Once
	file_proto_user_map_proto_rawDescData = file_proto_user_map_proto_rawDesc
)

func file_proto_user_map_proto_rawDescGZIP() []byte {
	file_proto_user_map_proto_rawDescOnce.Do(func() {
		file_proto_user_map_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_user_map_proto_rawDescData)
	})
	return file_proto_user_map_proto_rawDescData
}

var file_proto_user_map_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_user_map_proto_goTypes = []interface{}{
	(*UserMap)(nil), // 0: api.UserMap
	nil,             // 1: api.UserMap.PointsEntry
}
var file_proto_user_map_proto_depIdxs = []int32{
	1, // 0: api.UserMap.points:type_name -> api.UserMap.PointsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_user_map_proto_init() }
func file_proto_user_map_proto_init() {
	if File_proto_user_map_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_user_map_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_user_map_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_map_proto_goTypes,
		DependencyIndexes: file_proto_user_map_proto_depIdxs,
		MessageInfos:      file_proto_user_map_proto_msgTypes,
	}.Build()
	File_proto_user_map_proto = out.File
	file_proto_user_map_proto_rawDesc = nil
	file_proto_user_map_proto_goTypes = nil
	file_proto_user_map_proto_depIdxs = nil
}
