// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto/user_oneof.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserOneOf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//	*UserOneOf_A
	//	*UserOneOf_B
	Message isUserOneOf_Message `protobuf_oneof:"message"`
}

func (x *UserOneOf) Reset() {
	*x = UserOneOf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_oneof_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOneOf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOneOf) ProtoMessage() {}

func (x *UserOneOf) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_oneof_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOneOf.ProtoReflect.Descriptor instead.
func (*UserOneOf) Descriptor() ([]byte, []int) {
	return file_proto_user_oneof_proto_rawDescGZIP(), []int{0}
}

func (m *UserOneOf) GetMessage() isUserOneOf_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *UserOneOf) GetA() *MessageA {
	if x, ok := x.GetMessage().(*UserOneOf_A); ok {
		return x.A
	}
	return nil
}

func (x *UserOneOf) GetB() *MessageB {
	if x, ok := x.GetMessage().(*UserOneOf_B); ok {
		return x.B
	}
	return nil
}

type isUserOneOf_Message interface {
	isUserOneOf_Message()
}

type UserOneOf_A struct {
	A *MessageA `protobuf:"bytes,2,opt,name=a,proto3,oneof"`
}

type UserOneOf_B struct {
	B *MessageB `protobuf:"bytes,3,opt,name=b,proto3,oneof"`
}

func (*UserOneOf_A) isUserOneOf_Message() {}

func (*UserOneOf_B) isUserOneOf_Message() {}

type MessageA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title int64 `protobuf:"varint,1,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *MessageA) Reset() {
	*x = MessageA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_oneof_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageA) ProtoMessage() {}

func (x *MessageA) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_oneof_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageA.ProtoReflect.Descriptor instead.
func (*MessageA) Descriptor() ([]byte, []int) {
	return file_proto_user_oneof_proto_rawDescGZIP(), []int{1}
}

func (x *MessageA) GetTitle() int64 {
	if x != nil {
		return x.Title
	}
	return 0
}

type MessageB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *MessageB) Reset() {
	*x = MessageB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_oneof_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageB) ProtoMessage() {}

func (x *MessageB) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_oneof_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageB.ProtoReflect.Descriptor instead.
func (*MessageB) Descriptor() ([]byte, []int) {
	return file_proto_user_oneof_proto_rawDescGZIP(), []int{2}
}

func (x *MessageB) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_proto_user_oneof_proto protoreflect.FileDescriptor

var file_proto_user_oneof_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6f, 0x6e, 0x65,
	0x6f, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x54, 0x0a,
	0x09, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x12, 0x1d, 0x0a, 0x01, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x41, 0x48, 0x00, 0x52, 0x01, 0x61, 0x12, 0x1d, 0x0a, 0x01, 0x62, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x42, 0x48, 0x00, 0x52, 0x01, 0x62, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x20, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x20, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x42, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_user_oneof_proto_rawDescOnce sync.Once
	file_proto_user_oneof_proto_rawDescData = file_proto_user_oneof_proto_rawDesc
)

func file_proto_user_oneof_proto_rawDescGZIP() []byte {
	file_proto_user_oneof_proto_rawDescOnce.Do(func() {
		file_proto_user_oneof_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_user_oneof_proto_rawDescData)
	})
	return file_proto_user_oneof_proto_rawDescData
}

var file_proto_user_oneof_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_user_oneof_proto_goTypes = []interface{}{
	(*UserOneOf)(nil), // 0: api.UserOneOf
	(*MessageA)(nil),  // 1: api.MessageA
	(*MessageB)(nil),  // 2: api.MessageB
}
var file_proto_user_oneof_proto_depIdxs = []int32{
	1, // 0: api.UserOneOf.a:type_name -> api.MessageA
	2, // 1: api.UserOneOf.b:type_name -> api.MessageB
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_user_oneof_proto_init() }
func file_proto_user_oneof_proto_init() {
	if File_proto_user_oneof_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_user_oneof_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOneOf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_oneof_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_oneof_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_user_oneof_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*UserOneOf_A)(nil),
		(*UserOneOf_B)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_user_oneof_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_oneof_proto_goTypes,
		DependencyIndexes: file_proto_user_oneof_proto_depIdxs,
		MessageInfos:      file_proto_user_oneof_proto_msgTypes,
	}.Build()
	File_proto_user_oneof_proto = out.File
	file_proto_user_oneof_proto_rawDesc = nil
	file_proto_user_oneof_proto_goTypes = nil
	file_proto_user_oneof_proto_depIdxs = nil
}
