// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: student_enum.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StudentEnum_Gender int32

const (
	StudentEnum_FEMALE StudentEnum_Gender = 0
	StudentEnum_MALE   StudentEnum_Gender = 1
)

// Enum value maps for StudentEnum_Gender.
var (
	StudentEnum_Gender_name = map[int32]string{
		0: "FEMALE",
		1: "MALE",
	}
	StudentEnum_Gender_value = map[string]int32{
		"FEMALE": 0,
		"MALE":   1,
	}
)

func (x StudentEnum_Gender) Enum() *StudentEnum_Gender {
	p := new(StudentEnum_Gender)
	*p = x
	return p
}

func (x StudentEnum_Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StudentEnum_Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_student_enum_proto_enumTypes[0].Descriptor()
}

func (StudentEnum_Gender) Type() protoreflect.EnumType {
	return &file_student_enum_proto_enumTypes[0]
}

func (x StudentEnum_Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StudentEnum_Gender.Descriptor instead.
func (StudentEnum_Gender) EnumDescriptor() ([]byte, []int) {
	return file_student_enum_proto_rawDescGZIP(), []int{0, 0}
}

type StudentEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Gender StudentEnum_Gender `protobuf:"varint,2,opt,name=gender,proto3,enum=main.StudentEnum_Gender" json:"gender,omitempty"`
	Scores []int32            `protobuf:"varint,3,rep,packed,name=scores,proto3" json:"scores,omitempty"`
}

func (x *StudentEnum) Reset() {
	*x = StudentEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_student_enum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudentEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentEnum) ProtoMessage() {}

func (x *StudentEnum) ProtoReflect() protoreflect.Message {
	mi := &file_student_enum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentEnum.ProtoReflect.Descriptor instead.
func (*StudentEnum) Descriptor() ([]byte, []int) {
	return file_student_enum_proto_rawDescGZIP(), []int{0}
}

func (x *StudentEnum) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentEnum) GetGender() StudentEnum_Gender {
	if x != nil {
		return x.Gender
	}
	return StudentEnum_FEMALE
}

func (x *StudentEnum) GetScores() []int32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

var File_student_enum_proto protoreflect.FileDescriptor

var file_student_enum_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x8b, 0x01, 0x0a, 0x0b, 0x53,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x30,
	0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x75,
	0x6d, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x1e, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x45, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_student_enum_proto_rawDescOnce sync.Once
	file_student_enum_proto_rawDescData = file_student_enum_proto_rawDesc
)

func file_student_enum_proto_rawDescGZIP() []byte {
	file_student_enum_proto_rawDescOnce.Do(func() {
		file_student_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_student_enum_proto_rawDescData)
	})
	return file_student_enum_proto_rawDescData
}

var file_student_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_student_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_student_enum_proto_goTypes = []interface{}{
	(StudentEnum_Gender)(0), // 0: main.StudentEnum.Gender
	(*StudentEnum)(nil),     // 1: main.StudentEnum
}
var file_student_enum_proto_depIdxs = []int32{
	0, // 0: main.StudentEnum.gender:type_name -> main.StudentEnum.Gender
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_student_enum_proto_init() }
func file_student_enum_proto_init() {
	if File_student_enum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_student_enum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudentEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_student_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_student_enum_proto_goTypes,
		DependencyIndexes: file_student_enum_proto_depIdxs,
		EnumInfos:         file_student_enum_proto_enumTypes,
		MessageInfos:      file_student_enum_proto_msgTypes,
	}.Build()
	File_student_enum_proto = out.File
	file_student_enum_proto_rawDesc = nil
	file_student_enum_proto_goTypes = nil
	file_student_enum_proto_depIdxs = nil
}
