// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitApp() (*FooMessage, error) {
	message := ProvideMessage()
	beer := ProvideBeer()
	fooMessage := &FooMessage{
		Msg: message,
		Ber: beer,
	}
	return fooMessage, nil
}

// wire.go:

// 因为入参均是字符串类型, wire 无法区分具体的 string
// 所以这里我们使用自定义类型
type Message string

type Beer string

// 测试构造结构体
type FooMessage struct {
	Msg Message
	Ber Beer
}

func ProvideMessage() Message {
	return "info"
}

func ProvideBeer() Beer {
	return "xuehua666"
}
